// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: tsentrifuge_1

#include "ui.h"
#include "ui_helpers.h"
//////////////////// VARIABLES ////////////////////

int incvals[5] = {50,1,1,1,1};
int decvals[5] = {-50,-1,-1,-1,-1};
int incvalf[5] = {200,1,1,1,1};
int decvalf[5] = {-200,-1,-1,-1,-1};
int minval[5] = {300,1,0,1,0};
int maxval[5] = {6000,5,0,10,0};
int endofcycle = 1;

// SCREEN: ui_bootcreen
void ui_bootcreen_screen_init(void);
lv_obj_t * ui_bootcreen;
lv_obj_t * ui_Panel_name_device;
lv_obj_t * ui_Label_version;
lv_obj_t * ui_logopic;
lv_obj_t * ui_logospinner;


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_TabView1(lv_event_t * e);
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabCen;
lv_obj_t * ui_PanTimCen;
void ui_event_BtnTimDecC(lv_event_t * e);
lv_obj_t * ui_BtnTimDecC;
void ui_event_BtnTimIncC(lv_event_t * e);
lv_obj_t * ui_BtnTimIncC; 
lv_obj_t * ui_TxtTCen;
lv_obj_t * ui_LblTimCen;
lv_obj_t * ui_PanValCen;
void ui_event_BtnValDecC(lv_event_t * e);
lv_obj_t * ui_BtnValDecC;
void ui_event_BtnValIncC(lv_event_t * e);
lv_obj_t * ui_BtnValIncC;
lv_obj_t * ui_TxtVCen;
lv_obj_t * ui_LblValCen;
void ui_event_BtnPlaCen(lv_event_t * e);
lv_obj_t * ui_BtnPlaCen;
void ui_event_BtnStoCen(lv_event_t * e);
lv_obj_t * ui_BtnStoCen;
lv_obj_t * ui_TabVor;
lv_obj_t * ui_PanlTimVor;
void ui_event_BtnTimDecV(lv_event_t * e);
lv_obj_t * ui_BtnTimDecV;
void ui_event_BtnTimIncV(lv_event_t * e);
lv_obj_t * ui_BtnTimIncV;
lv_obj_t * ui_TxtTVor;
lv_obj_t * ui_LblTimVor;
lv_obj_t * ui_PanelValVor;
void ui_event_BtnValDecV(lv_event_t * e);
lv_obj_t * ui_BtnValDecV;
void ui_event_BtnValIncV(lv_event_t * e);
lv_obj_t * ui_BtnValIncV;
lv_obj_t * ui_TxtVVor;
lv_obj_t * ui_LblValVor;
void ui_event_BtnPlaVor(lv_event_t * e);
lv_obj_t * ui_BtnPlaVor;
void ui_event_BtnStoVor(lv_event_t * e);
lv_obj_t * ui_BtnStoVor;
lv_obj_t * ui_TabCom;
void ui_event_TabView2(lv_event_t * e);
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TP1;
void ui_event_DrpDwn1(lv_event_t * e);
lv_obj_t * ui_TxtTim1;
void ui_event_BtnTimInc1(lv_event_t * e);
lv_obj_t * ui_BtnTimInc1;
void ui_event_BtnTimDec1(lv_event_t * e);
lv_obj_t * ui_BtnTimDec1;
void ui_event_BtnValDec1(lv_event_t * e);
lv_obj_t * ui_BtnValDec1;
void ui_event_BtnValInc1(lv_event_t * e);
lv_obj_t * ui_BtnValInc1;
lv_obj_t * ui_TxtVal1;
void ui_event_BtnPla1(lv_event_t * e);
lv_obj_t * ui_BtnPla1;
void ui_event_BtnSto1(lv_event_t * e);
lv_obj_t * ui_BtnSto1;
lv_obj_t * ui_TP2;
void ui_event_DrpDwn2(lv_event_t * e);
lv_obj_t * ui_TxtTim2;
void ui_event_BtnTimInc2(lv_event_t * e);
lv_obj_t * ui_BtnTimInc2;
void ui_event_BtnTimDec2(lv_event_t * e);
lv_obj_t * ui_BtnTimDec2;
void ui_event_BtnValDec2(lv_event_t * e);
lv_obj_t * ui_BtnValDec2;
void ui_event_BtnValInc2(lv_event_t * e);
lv_obj_t * ui_BtnValInc2;
lv_obj_t * ui_TxtVal2;
void ui_event_BtnPla2(lv_event_t * e);
lv_obj_t * ui_BtnPla2;
void ui_event_BtnSto2(lv_event_t * e);
lv_obj_t * ui_BtnSto2;
lv_obj_t * ui_TP3;
void ui_event_DrpDwn3(lv_event_t * e);
lv_obj_t * ui_TxtTim3;
void ui_event_BtnTimInc3(lv_event_t * e);
lv_obj_t * ui_BtnTimInc3;
void ui_event_BtnTimDec3(lv_event_t * e);
lv_obj_t * ui_BtnTimDec3;
void ui_event_BtnValDec3(lv_event_t * e);
lv_obj_t * ui_BtnValDec3;
void ui_event_BtnValInc3(lv_event_t * e);
lv_obj_t * ui_BtnValInc3;
lv_obj_t * ui_TxtVal3;
void ui_event_BtnPla3(lv_event_t * e);
lv_obj_t * ui_BtnPla3;
void ui_event_BtnSto3(lv_event_t * e);
lv_obj_t * ui_BtnSto3;
lv_obj_t * ui_TP4;
void ui_event_DrpDwn4(lv_event_t * e);
lv_obj_t * ui_TxtTim4;
void ui_event_BtnTimInc4(lv_event_t * e);
lv_obj_t * ui_BtnTimInc4;
void ui_event_BtnTimDec4(lv_event_t * e);
lv_obj_t * ui_BtnTimDec4;
lv_obj_t * ui_PanlVal4;
void ui_event_BtnValDec4(lv_event_t * e);
lv_obj_t * ui_BtnValDec4;
void ui_event_BtnValInc4(lv_event_t * e);
lv_obj_t * ui_BtnValInc4;
lv_obj_t * ui_TxtVal4;
void ui_event_BtnPla4(lv_event_t * e);
lv_obj_t * ui_BtnPla4;
void ui_event_BtnSto4(lv_event_t * e);
lv_obj_t * ui_BtnSto4;
lv_obj_t * ui_TP5;
void ui_event_DrpDwn5(lv_event_t * e);
lv_obj_t * ui_TxtTim5;
void ui_event_BtnTimInc5(lv_event_t * e);
lv_obj_t * ui_BtnTimInc5;
void ui_event_BtnTimDec5(lv_event_t * e);
lv_obj_t * ui_BtnTimDec5;
void ui_event_BtnValDec5(lv_event_t * e);
lv_obj_t * ui_BtnValDec5;
void ui_event_BtnValInc5(lv_event_t * e);
lv_obj_t * ui_BtnValInc5;
lv_obj_t * ui_TxtVal5;
void ui_event_BtnPla5(lv_event_t * e);
lv_obj_t * ui_BtnPla5;
void ui_event_BtnSto5(lv_event_t * e);
lv_obj_t * ui_BtnSto5;
lv_obj_t * ui_Hider;
lv_obj_t * ui_Hider1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_x[1] = {&ui_img_35x35_png};
const lv_img_dsc_t * ui_imgset_1266485886[1] = {&ui_img_450824764};
const lv_img_dsc_t * ui_imgset_47409148[1] = {&ui_img_9854092};
const lv_img_dsc_t * ui_imgset_38357866[1] = {&ui_img_928063594};
const lv_img_dsc_t * ui_imgset_844927572[1] = {&ui_img_224489140};
const lv_img_dsc_t * ui_imgset_670263864[1] = {&ui_img_1846787616};
const lv_img_dsc_t * ui_imgset_1183047569[3] = {&ui_img_2007371332, &ui_img_852219735, &ui_img_551207074};

lv_obj_t * ui_LblVal[5];
lv_obj_t * ui_LblTim[5];
lv_obj_t * ui_DrpDwn[5];
lv_obj_t * ui_PanlVal[5];
lv_obj_t * ui_PanTim[5];

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_TabView1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        UPDATE_TAB1(e);
        stopflag=1;
        startflag=0;
        endofcycle=1;
    }
}
void ui_event_BtnTimDecC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&centrifuge.timeset, 0, 3600, -10, ui_LblTimCen);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&centrifuge.timeset, 0, 3600, -30, ui_LblTimCen);
    }
}
void ui_event_BtnTimIncC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&centrifuge.timeset, 0, 3600, 30, ui_LblTimCen);
    }
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&centrifuge.timeset, 0, 3600, 10, ui_LblTimCen);
    }
}
void ui_event_BtnValDecC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&centrifuge.value,300,6000,-50,ui_LblValCen);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&centrifuge.value,300,6000,-200,ui_LblValCen);
    }
}
void ui_event_BtnValIncC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&centrifuge.value,300,6000,50,ui_LblValCen);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&centrifuge.value,300,6000,200,ui_LblValCen);
    }
}
void ui_event_BtnPlaCen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PAUSE_CEN(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        startflag=1;
        pauseflag=0;  
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        START_CEN(e);
        pauseflag=1;    
    }
}
void ui_event_BtnStoCen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        STOP_CEN(e);
        _ui_state_modify(ui_BtnPlaCen, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        stopflag=1;
        endofcycle=1;
    }
}
void ui_event_BtnTimDecV(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&vortex.timeset, 0, 3600, -10, ui_LblTimVor);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&vortex.timeset, 0, 3600, -30, ui_LblTimVor);
    }
}
void ui_event_BtnTimIncV(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&vortex.timeset, 0, 3600, 10, ui_LblTimVor);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&vortex.timeset, 0, 3600, 30, ui_LblTimVor);
    }
}
void ui_event_BtnValDecV(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&vortex.value,1,5,-1,ui_LblValVor);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&vortex.value,1,5,-1,ui_LblValVor);
    }
}
void ui_event_BtnValIncV(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&vortex.value,1,5,1,ui_LblValVor);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&vortex.value,1,5,1,ui_LblValVor);
    }
}
void ui_event_BtnPlaVor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        START_VOR(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        startflag=1;
        pauseflag=0;  
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PAUSE_VOR(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        pauseflag=1;    
    }
}
void ui_event_BtnStoVor(lv_event_t * e) 
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        STOP_VOR(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_BtnPlaVor, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        stopflag=1;
        endofcycle=1;
    }
}
void ui_event_TabView2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        UPDATE_TAB2(e);
    }
}
void ui_event_DrpDwn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        UPDATE_DD(e);
        program[0].mode = lv_dropdown_get_selected(ui_DrpDwn[0]);
    }
}
void ui_event_BtnTimInc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[0].timeset, 0, 3600, 30, ui_LblTim[0]);
    }
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[0].timeset, 0, 3600, 10, ui_LblTim[0]);
    }
}
void ui_event_BtnTimDec1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[0].timeset, 0, 3600, -10, ui_LblTim[0]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[0].timeset, 0, 3600, -30, ui_LblTim[0]);
    }
}
void ui_event_BtnValDec1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[0].value,minval[program[0].mode],maxval[program[0].mode],decvals[program[0].mode],ui_LblVal[0]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[0].value,minval[program[0].mode],maxval[program[0].mode],decvalf[program[0].mode],ui_LblVal[0]);
    }
}
void ui_event_BtnValInc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[0].value,minval[program[0].mode],maxval[program[0].mode],incvals[program[0].mode],ui_LblVal[0]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[0].value,minval[program[0].mode],maxval[program[0].mode],incvalf[program[0].mode],ui_LblVal[0]);
    }
}
void ui_event_BtnPla1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        START_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        startflag=1;
        pauseflag=0;        
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PAUSE_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        pauseflag=1; 
    }
}
void ui_event_BtnSto1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        STOP_COM(e);
        _ui_state_modify(ui_BtnPla1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        stopflag=1;
        endofcycle=1;
    }
}
void ui_event_DrpDwn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        UPDATE_DD(e);
        program[1].mode = lv_dropdown_get_selected(ui_DrpDwn[1]);
    }
}
void ui_event_BtnTimInc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[1].timeset, 0, 3600, 30, ui_LblTim[1]);
    }
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[1].timeset, 0, 3600, 10, ui_LblTim[1]);
    }
}
void ui_event_BtnTimDec2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[1].timeset, 0, 3600, -10, ui_LblTim[1]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[1].timeset, 0, 3600, -30, ui_LblTim[1]);
    }
}
void ui_event_BtnValDec2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[1].value,minval[program[1].mode],maxval[program[1].mode],decvals[program[1].mode],ui_LblVal[1]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[1].value,minval[program[1].mode],maxval[program[1].mode],decvalf[program[1].mode],ui_LblVal[1]);
    }
}
void ui_event_BtnValInc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[1].value,minval[program[1].mode],maxval[program[1].mode],incvals[program[1].mode],ui_LblVal[1]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[1].value,minval[program[1].mode],maxval[program[1].mode],incvalf[program[1].mode],ui_LblVal[1]);
    }
}
void ui_event_BtnPla2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        START_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        startflag=1;
        pauseflag=0;        
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PAUSE_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        pauseflag=1;        
    }
}
void ui_event_BtnSto2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        STOP_COM(e);
        _ui_state_modify(ui_BtnPla1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        stopflag=1;
        endofcycle=1;
    }
}
void ui_event_DrpDwn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        UPDATE_DD(e);
        program[2].mode = lv_dropdown_get_selected(ui_DrpDwn[2]);
    }
}
void ui_event_BtnTimInc3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[2].timeset, 0, 3600, 30, ui_LblTim[2]);
    }
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[2].timeset, 0, 3600, 10, ui_LblTim[2]);
    }
}
void ui_event_BtnTimDec3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[2].timeset, 0, 3600, -10, ui_LblTim[2]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[2].timeset, 0, 3600, -30, ui_LblTim[2]);
    }
}
void ui_event_BtnValDec3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[2].value,minval[program[2].mode],maxval[program[2].mode],decvals[program[2].mode],ui_LblVal[2]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[2].value,minval[program[2].mode],maxval[program[2].mode],decvalf[program[2].mode],ui_LblVal[2]);
    }
}
void ui_event_BtnValInc3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[2].value,minval[program[2].mode],maxval[program[2].mode],incvals[program[2].mode],ui_LblVal[2]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[2].value,minval[program[2].mode],maxval[program[2].mode],incvalf[program[2].mode],ui_LblVal[2]);
    }
}
void ui_event_BtnPla3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        START_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        startflag=1;
        pauseflag=0;    
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PAUSE_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        pauseflag=1;
    }
}
void ui_event_BtnSto3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        STOP_COM(e);
        _ui_state_modify(ui_BtnPla1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        stopflag=1;
        endofcycle=1;
    }
}
void ui_event_DrpDwn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        UPDATE_DD(e);
        program[3].mode = lv_dropdown_get_selected(ui_DrpDwn[3]);
    }
}
void ui_event_BtnTimInc4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[3].timeset, 0, 3600, 30, ui_LblTim[3]);
    }
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[3].timeset, 0, 3600, 10, ui_LblTim[3]);
    }
}
void ui_event_BtnTimDec4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[3].timeset, 0, 3600, -10, ui_LblTim[3]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[3].timeset, 0, 3600, -30, ui_LblTim[3]);
    }
}
void ui_event_BtnValDec4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[3].value,minval[program[3].mode],maxval[program[3].mode],decvals[program[3].mode],ui_LblVal[3]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[3].value,minval[program[3].mode],maxval[program[3].mode],decvalf[program[3].mode],ui_LblVal[3]);
    }
}
void ui_event_BtnValInc4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[3].value,minval[program[3].mode],maxval[program[3].mode],incvals[program[3].mode],ui_LblVal[3]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[3].value,minval[program[3].mode],maxval[program[3].mode],incvalf[program[3].mode],ui_LblVal[3]);
    }
}
void ui_event_BtnPla4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        START_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        startflag=1;
        pauseflag=0;
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PAUSE_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        pauseflag=1;
    }
}
void ui_event_BtnSto4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        STOP_COM(e);
        _ui_state_modify(ui_BtnPla1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        stopflag=1;
        endofcycle=1;
    }
}
void ui_event_DrpDwn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        UPDATE_DD(e);
        program[4].mode = lv_dropdown_get_selected(ui_DrpDwn[4]);
    }
}
void ui_event_BtnTimInc5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[5].timeset, 0, 3600, 30, ui_LblTim[4]);
    }
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[5].timeset, 0, 3600, 10, ui_LblTim[4]);
    }
}
void ui_event_BtnTimDec5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustTime(&program[5].timeset, 0, 3600, -10, ui_LblTim[4]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustTime(&program[5].timeset, 0, 3600, -30, ui_LblTim[4]);
    }
}
void ui_event_BtnValDec5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[4].value,minval[program[4].mode],maxval[program[4].mode],decvals[program[4].mode],ui_LblVal[4]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[4].value,minval[program[4].mode],maxval[program[4].mode],decvalf[program[4].mode],ui_LblVal[4]);
    }
}
void ui_event_BtnValInc5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adjustValue(&program[4].value,minval[program[4].mode],maxval[program[4].mode],incvals[program[4].mode],ui_LblVal[4]);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        adjustValue(&program[4].value,minval[program[4].mode],maxval[program[4].mode],incvalf[program[4].mode],ui_LblVal[4]);
    }
}
void ui_event_BtnPla5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        START_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        startflag=1;
        pauseflag=0;
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        PAUSE_COM(e);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        pauseflag=1;
    }
}
void ui_event_BtnSto5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        STOP_COM(e);
        _ui_state_modify(ui_BtnPla1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BtnPla5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_BtnPla5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Hider, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Hider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        stopflag=1;
        endofcycle=1;
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_bootcreen_screen_init();
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_bootcreen);
}
