// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: tsentrifuge_1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void UPDATE_TAB1(lv_event_t * e);
void TIME_DEC(lv_event_t * e);
void TIME_INC(lv_event_t * e);
void VALUE_DEC(lv_event_t * e);
void VALUE_INC(lv_event_t * e);
void PAUSE_CEN(lv_event_t * e);
void START_CEN(lv_event_t * e);
void STOP_CEN(lv_event_t * e);
void START_VOR(lv_event_t * e);
void PAUSE_VOR(lv_event_t * e);
void STOP_VOR(lv_event_t * e);
void UPDATE_TAB2(lv_event_t * e);
void UPDATE_DD(lv_event_t * e);
void START_COM(lv_event_t * e);
void PAUSE_COM(lv_event_t * e);
void STOP_COM(lv_event_t * e);
void adjustTime(int *timeset, int minValue, int maxValue, int delta, lv_obj_t *label);
void adjustValue(int *value, int minValue, int maxValue, int delta, lv_obj_t *label);
void updateTimeLabel(lv_obj_t *label, int timeset);
void updateLabel(lv_obj_t *label, int value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
