// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: tsentrifuge_1

#include "ui.h"
#include "stdio.h"

void updateLabel(lv_obj_t *label, int value) 
{
    char buffer[10];
    sprintf(buffer, "%3d", value);
    lv_label_set_text(label, buffer);
}

void updateTimeLabel(lv_obj_t *label, int timeset) 
{
    char buffer[10];
    sprintf(buffer, "%02d:%02d", timeset / 60, timeset % 60);
    lv_label_set_text(label, buffer);
}

void adjustValue(int *value, int minValue, int maxValue, int delta, lv_obj_t *label) 
{
    Buzzer(50);
    if(delta>0){    
        if ( *value < (maxValue)) 
        {
            *value += delta;
            updateLabel(label, *value);
        }else
        {
            *value = maxValue;
        }
    }else if(delta<0){
        if (*value > (minValue)) 
        {
            *value += delta;
            updateLabel(label, *value);
        }
        else 
        {
            *value = minValue;
        }
    }
    {
        if (*value < minValue) 
        {
            *value = minValue;
            updateLabel(label, *value);
        }else if(*value > maxValue)
        {
            *value = maxValue;
            updateLabel(label, *value);
        }

    }       
}

void adjustTime(int *timeset, int minValue, int maxValue, int delta, lv_obj_t *label) 
{
    Buzzer(50);
    if(delta>0){
        if (*timeset <= (maxValue-delta)) 
        {
        *timeset += delta;
        updateTimeLabel(label, *timeset);
        }    
    }else if(delta<0){
        if (*timeset >= (minValue-delta)) 
        {
            *timeset += delta;
            updateTimeLabel(label, *timeset);
        }
    }else{
		if (*timeset < minValue) 
        {
            *timeset = minValue;
            updateTimeLabel(label, *timeset);
        }else
        {
            *timeset = maxValue;
            updateTimeLabel(label, *timeset);
        }

	}

}

void VALUE_DEC(lv_event_t * e)
{
	// Your code here
}

void VALUE_INC(lv_event_t * e)
{
	// Your code here
}

void PAUSE_CEN(lv_event_t * e)
{
	// Your code here
}

void START_CEN(lv_event_t * e)
{
	// Your code here
}

void STOP_CEN(lv_event_t * e)
{
	// Your code here
}

void START_VOR(lv_event_t * e)
{
	// Your code here
}

void PAUSE_VOR(lv_event_t * e)
{
	// Your code here
}

void STOP_VOR(lv_event_t * e)
{
	// Your code here
}

void Tab2update(lv_event_t * e)
{
	// Your code here
}

void UPDATE_DD(lv_event_t * e)
{
    tab2 = lv_tabview_get_tab_act(ui_TabView2);// Your code here
    modesel = program[tab2].mode = lv_dropdown_get_selected(ui_DrpDwn[tab2]);
    adjustValue(&program[tab2].value, minval[modesel], maxval[modesel],0, ui_LblVal[tab2]);
    switch (program[tab2].mode)
    {
    case 2:
        _ui_flag_modify(ui_PanTim[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);    
        _ui_flag_modify(ui_PanlVal[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        /* code */
        break;
    case 3:
        _ui_flag_modify(ui_PanlVal[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PanTim[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        /* code */
        break;
    case 4:
        _ui_flag_modify(ui_PanlVal[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PanTim[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        /* code */
        break;
    default:
        _ui_flag_modify(ui_PanlVal[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PanTim[tab2], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);     
        break;
    }
}

void START_COM(lv_event_t * e)
{
	// Your code here
}

void PAUSE_COM(lv_event_t * e)
{
	// Your code here
}

void STOP_COM(lv_event_t * e)
{
	// Your code here
}

void UPDATE_TAB1(lv_event_t * e)
{
	tab1 = lv_tabview_get_tab_act(ui_TabView1);
}

void UPDATE_TAB2(lv_event_t * e)
{
	tab2 = lv_tabview_get_tab_act(ui_TabView2);
}
